artifacts:
    ARTIFACTS_DIR: artifacts
    BASE_MODEL_DIR: base_model
    BASE_MODEL_NAME: resnet50.h5
    UPDATED_BASE_MODEL_NAME: resnet50_updated.h5
    CHECKPOINT_DIR: checkpoints
    BASE_LOG_DIR: base_model_dir
    TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
    CALLBACKS_DIR: callbacks
    TRAINED_MODEL_DIR: model
    DATA_DIR: data
    data_subset_train: train
    data_subset_test: val
